#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7.1 effective-4.2 (swiftlang-5.7.1.134.3 clang-1400.0.29.51)
#ifndef AP_PAYSDK_SWIFT_H
#define AP_PAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import StoreKit;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AP_PaySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, ApplePayButtonStyle, open) {
  ApplePayButtonStyleWhite = 0,
  ApplePayButtonStyleWhiteOutline = 1,
  ApplePayButtonStyleBlack = 2,
};

typedef SWIFT_ENUM(NSInteger, ApplePayButtonType, open) {
  ApplePayButtonTypePlain = 0,
  ApplePayButtonTypeBuy = 1,
  ApplePayButtonTypeSetUp = 2,
  ApplePayButtonTypeInStore = 3,
  ApplePayButtonTypeDonate = 4,
  ApplePayButtonTypeCheckout = 5,
  ApplePayButtonTypeBook = 6,
  ApplePayButtonTypeSubscribe = 7,
};

@class NSString;

SWIFT_PROTOCOL("_TtP9AP_PaySDK19PaySDKCustomization_")
@protocol PaySDKCustomization
- (BOOL)setTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK25PaySDKButtonCustomization_")
@protocol PaySDKButtonCustomization <PaySDKCustomization>
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonName:(NSString * _Nonnull)buttonName error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getButtonName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK13Customization")
@interface Customization : NSObject <PaySDKCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK19ButtonCustomization")
@interface ButtonCustomization : Customization <PaySDKButtonCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSInteger)cornerRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSInteger)cornerRadius :(NSString * _Nonnull)buttonName OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonName:(NSString * _Nonnull)buttonName error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getButtonName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("CallBackParam")
@interface CallBackParam : NSObject
- (nonnull instancetype)initWithSuccessUrl:(NSString * _Nonnull)successUrl cancelUrl:(NSString * _Nonnull)cancelUrl errorUrl:(NSString * _Nonnull)errorUrl failUrl:(NSString * _Nonnull)failUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CardDetails")
@interface CardDetails : NSObject
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNo:(NSString * _Nonnull)cardNo expMonth:(NSString * _Nonnull)expMonth expYear:(NSString * _Nonnull)expYear securityCode:(NSString * _Nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9AP_PaySDK5Cards")
@interface Cards : NSObject
/// Instantiate the instance using the passed dictionary values to set the properties values
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CurrencyCode, open) {
  CurrencyCodeHKD = 0,
  CurrencyCodeUSD = 1,
  CurrencyCodeSGD = 2,
  CurrencyCodeRMB = 3,
  CurrencyCodeCNY = 4,
  CurrencyCodeYEN = 5,
  CurrencyCodeJPY = 6,
  CurrencyCodeTWD = 7,
  CurrencyCodeAUD = 8,
  CurrencyCodeEUR = 9,
  CurrencyCodeGBP = 10,
  CurrencyCodeCAD = 11,
  CurrencyCodeMOP = 12,
  CurrencyCodePHP = 13,
  CurrencyCodeTHB = 14,
  CurrencyCodeIDR = 15,
  CurrencyCodeBND = 16,
  CurrencyCodeMYR = 17,
  CurrencyCodeBRL = 18,
  CurrencyCodeINR = 19,
  CurrencyCodeTRY = 20,
  CurrencyCodeZAR = 21,
  CurrencyCodeVND = 22,
  CurrencyCodeLKR = 23,
  CurrencyCodeKWD = 24,
  CurrencyCodeNZD = 25,
};




typedef SWIFT_ENUM(NSInteger, EnvType, open) {
  EnvTypeSANDBOX = 0,
  EnvTypePRODUCTION = 1,
};


SWIFT_CLASS("_TtC9AP_PaySDK26GlobalJsIntegrateViewModel")
@interface GlobalJsIntegrateViewModel : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified tncUrl;
@property (nonatomic, copy) NSString * _Null_unspecified showInApp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK24PaySDKLabelCustomization_")
@protocol PaySDKLabelCustomization <PaySDKCustomization>
- (BOOL)setHeadingTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK18LabelCustomization")
@interface LabelCustomization : Customization <PaySDKLabelCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)headingTextColor :(NSString * _Nonnull)headingTextFontName :(NSInteger)headingTextFontSize OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setHeadingTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, Language, open) {
  LanguageENGLISH = 0,
  LanguageCHINESE_TRADITIONAL = 1,
  LanguageCHINESE_SIMPLIFIED = 2,
  LanguageJAPANESE = 3,
  LanguageTHAI = 4,
  LanguageFRENCH = 5,
  LanguageGERMAN = 6,
  LanguageRUSSIAN = 7,
  LanguageSPANISH = 8,
  LanguageVIETNAMESE = 9,
};


SWIFT_CLASS("_TtC9AP_PaySDK7Methods")
@interface Methods : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("OrderId")
@interface OrderId : NSObject
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PayChannel, open) {
  PayChannelWEBVIEW = 0,
  PayChannelDIRECT = 1,
  PayChannelEASYPAYMENTFORM = 2,
  PayChannelNONE = 3,
};

@class PresentViewController;
@class ThreeDSParams;
enum PayGate : NSInteger;
enum payType : NSInteger;

SWIFT_CLASS_NAMED("PayData")
@interface PayData : NSObject
@property (nonatomic, strong) PresentViewController * _Nullable presentController;
@property (nonatomic, strong) CardDetails * _Nullable cardDetails;
@property (nonatomic, strong) CallBackParam * _Nullable callBackParam;
@property (nonatomic, strong) ThreeDSParams * _Nullable threeDSParams;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithChannelType:(enum PayChannel)channelType envType:(enum EnvType)envType amount:(NSString * _Nonnull)amount payGate:(enum PayGate)payGate currCode:(enum CurrencyCode)currCode payType:(enum payType)payType orderRef:(NSString * _Nonnull)orderRef payMethod:(NSString * _Nonnull)payMethod lang:(enum Language)lang merchantId:(NSString * _Nonnull)merchantId remark:(NSString * _Nonnull)remark payRef:(NSString * _Nonnull)payRef resultpage:(NSString * _Nonnull)resultpage showCloseButton:(BOOL)showCloseButton showToolbar:(BOOL)showToolbar webViewClosePrompt:(NSString * _Nonnull)webViewClosePrompt extraData:(NSDictionary<NSString *, id> * _Nullable)extraData merchantCapabilitiesData:(PKMerchantCapability)merchantCapabilitiesData supportedNetworksData:(NSArray<PKPaymentNetwork> * _Nonnull)supportedNetworksData OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM(NSInteger, PayGate, open) {
  PayGatePAYDOLLAR = 0,
  PayGatePESOPAY = 1,
  PayGateSIAMPAY = 2,
};


SWIFT_CLASS("_TtC9AP_PaySDK9PayResult")
@interface PayResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified amount;
@property (nonatomic, copy) NSString * _Null_unspecified successCode;
@property (nonatomic, copy) NSString * _Nullable maskedCardNo;
@property (nonatomic, copy) NSString * _Null_unspecified authId;
@property (nonatomic, copy) NSString * _Null_unspecified cardHolder;
@property (nonatomic, copy) NSString * _Null_unspecified currencyCode;
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
@property (nonatomic, copy) NSString * _Null_unspecified ord;
@property (nonatomic, copy) NSString * _Null_unspecified payRef;
@property (nonatomic, copy) NSString * _Null_unspecified prc;
@property (nonatomic, copy) NSString * _Null_unspecified ref;
@property (nonatomic, copy) NSString * _Null_unspecified src;
@property (nonatomic, copy) NSString * _Null_unspecified transactionTime;
@property (nonatomic, copy) NSString * _Null_unspecified descriptionStr;
@property (nonatomic, copy) NSString * _Nullable orderId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@protocol PaySDKDelegate;
@class UiCustomization;
@class NSURL;

SWIFT_CLASS_NAMED("PaySDK") SWIFT_AVAILABILITY(ios,introduced=10.0)
@interface PaySDK : NSObject <SKStoreProductViewControllerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PaySDK * _Nonnull shared;)
+ (PaySDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(PaySDK * _Nonnull)value;
@property (nonatomic, strong) id <PaySDKDelegate> _Nullable delegate;
@property (nonatomic, strong) PayData * _Null_unspecified paymentDetails;
@property (nonatomic, strong) UiCustomization * _Nullable uiCustomization;
@property (nonatomic) BOOL isBioMetricRequired;
@property (nonatomic) BOOL useSDKProgressScreen;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (void)queryWithAction:(NSString * _Nonnull)action;
- (void)process;
- (void)processOrderWithUrl:(NSURL * _Nonnull)url;
@end


typedef SWIFT_ENUM(NSInteger, PaySDKButtonType, open) {
  PaySDKButtonTypeSUBMIT = 0,
  PaySDKButtonTypeCONTINUE = 1,
  PaySDKButtonTypeNEXT = 2,
  PaySDKButtonTypeCANCEL = 3,
  PaySDKButtonTypeRESEND = 4,
};


@class TransQueryResults;
@class PaymentOptionsDetail;
@class UIImage;
@class UIViewController;

SWIFT_PROTOCOL("_TtP9AP_PaySDK14PaySDKDelegate_")
@protocol PaySDKDelegate
- (void)paymentResultWithResult:(PayResult * _Nonnull)result;
- (void)transQueryResultsWithResult:(TransQueryResults * _Nonnull)result;
- (void)payMethodOptionsWithMethod:(PaymentOptionsDetail * _Nonnull)method;
@optional
- (void)showProgress;
- (void)hideProgress;
- (UIImage * _Nullable)setMerchantInfoImg SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)setMerchantInfoScreen SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)setMerchantInfo SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_PROTOCOL("_TtP9AP_PaySDK26PaySDKTextBoxCustomization_")
@protocol PaySDKTextBoxCustomization <PaySDKCustomization>
- (BOOL)setBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBorderColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getBorderColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK26PaySDKToolbarCustomization_")
@protocol PaySDKToolbarCustomization <PaySDKCustomization>
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeaderText:(NSString * _Nonnull)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRightBarButtonText:(NSString * _Nonnull)rightBarButtonText error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getRightBarButtonText SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK21PaySDKUiCustomization_")
@protocol PaySDKUiCustomization
- (BOOL)setButtonCustomization:(id <PaySDKButtonCustomization> _Nonnull)buttonCustomization :(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomization:(id <PaySDKToolbarCustomization> _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomization:(id <PaySDKLabelCustomization> _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomization:(id <PaySDKTextBoxCustomization> _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (id <PaySDKButtonCustomization> _Nullable)getButtonCustomization:(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKToolbarCustomization> _Nullable)getToolbarCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKLabelCustomization> _Nullable)getLabelCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKTextBoxCustomization> _Nullable)getTextBoxCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK20PaymentOptionsDetail")
@interface PaymentOptionsDetail : NSObject
@property (nonatomic, strong) Methods * _Null_unspecified methods;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PresentViewController")
@interface PresentViewController : NSObject
- (nonnull instancetype)initWithPresentViewController:(UIViewController * _Nonnull)presentViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9AP_PaySDK20TextBoxCustomization")
@interface TextBoxCustomization : Customization <PaySDKTextBoxCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSInteger)borderWidth :(NSString * _Nonnull)borderColor :(NSInteger)cornerRadius OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBorderColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getBorderColor SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9AP_PaySDK13ThreeDSParams") SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface ThreeDSParams : NSObject
@property (nonatomic, copy) NSString * _Nullable threeDSCustomerEmail;
@property (nonatomic, copy) NSString * _Nullable threeDSDeliveryEmail;
@property (nonatomic, copy) NSString * _Nullable threeDSMobilePhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSMobilePhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSHomePhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSHomePhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSWorkPhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSWorkPhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingState;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingCity;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine1;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine2;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine3;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingPostalCode;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingDetails;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingState;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingCity;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine1;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine2;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine3;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctCreateDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAgeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctLastChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctLastChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPwChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPwChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPurchaseCount;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctCardProvisionAttempt;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctNumTransDay;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctNumTransYear;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPaymentAcctDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPaymentAcctInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctShippingAddrLastChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctShippingAddrLastChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctIsShippingAcctNameSame;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctIsSuspiciousAcct;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAuthMethod;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAuthTimestamp;
@property (nonatomic, copy) NSString * _Nullable threeDSDeliveryTime;
@property (nonatomic, copy) NSString * _Nullable threeDSPreOrderReason;
@property (nonatomic, copy) NSString * _Nullable threeDSPreOrderReadyDate;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardAmount;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardCurr;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardCount;
@property (nonatomic, copy) NSString * _Nullable threeDSSdkMaxTimeout;
@property (nonatomic, copy) NSString * _Nullable threeDSSdkInterface;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AP_PaySDK20ToolbarCustomization")
@interface ToolbarCustomization : Customization <PaySDKToolbarCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSString * _Nonnull)headerText :(NSString * _Nonnull)rightBarButtonText OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeaderText:(NSString * _Nonnull)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRightBarButtonText:(NSString * _Nonnull)rightBarButtonText error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getRightBarButtonText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("TransQueryResult")
@interface TransQueryResult : NSObject
@property (nonatomic, copy) NSString * _Nullable cur;
@property (nonatomic, copy) NSString * _Nullable txTime;
@property (nonatomic, copy) NSString * _Nullable errMsg;
@property (nonatomic, copy) NSString * _Nullable orderStatus;
@property (nonatomic, copy) NSString * _Nullable amt;
@property (nonatomic, copy) NSString * _Nullable remark;
@property (nonatomic, copy) NSString * _Nullable eci;
@property (nonatomic, copy) NSString * _Nullable ipCountry;
@property (nonatomic, copy) NSString * _Nullable channelType;
@property (nonatomic, copy) NSString * _Nullable merchantId;
@property (nonatomic, copy) NSString * _Nullable authId;
@property (nonatomic, copy) NSString * _Nullable payerAuth;
@property (nonatomic, copy) NSString * _Nullable panLast4;
@property (nonatomic, copy) NSString * _Nullable ref;
@property (nonatomic, copy) NSString * _Nullable payMethod;
@property (nonatomic, copy) NSString * _Nullable successcode;
@property (nonatomic, copy) NSString * _Nullable cardIssuingCountry;
@property (nonatomic, copy) NSString * _Nullable prc;
@property (nonatomic, copy) NSString * _Nullable ord;
@property (nonatomic, copy) NSString * _Nullable panFirst4;
@property (nonatomic, copy) NSString * _Nullable alertCode;
@property (nonatomic, copy) NSString * _Nullable src;
@property (nonatomic, copy) NSString * _Nullable payRef;
@property (nonatomic, copy) NSString * _Nullable holder;
@property (nonatomic, copy) NSString * _Nullable sourceIp;
+ (NSArray<TransQueryResult *> * _Nonnull)modelsFromDictionaryArrayWithArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
/// Returns the dictionary representation for the current instance.
///
/// returns:
/// NSDictionary.
- (NSDictionary * _Nonnull)dictionaryRepresentation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TransQueryResults")
@interface TransQueryResults : NSObject
@property (nonatomic, copy) NSArray<TransQueryResult *> * _Nullable detail;
@property (nonatomic, copy) NSString * _Nullable errMsg;
@property (nonatomic, copy) NSString * _Nullable resultCode;
+ (NSArray<TransQueryResults *> * _Nonnull)modelsFromDictionaryArrayWithArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


@class UIView;

@interface UIButton (SWIFT_EXTENSION(AP_PaySDK))
- (void)setApplePayButtonWithBtnType:(enum ApplePayButtonType)btnType btnStyle:(enum ApplePayButtonStyle)btnStyle inView:(UIView * _Nonnull)inView;
@end



@interface UIColor (SWIFT_EXTENSION(AP_PaySDK))
- (nullable instancetype)initWithHex:(NSString * _Nonnull)hex;
@end











SWIFT_CLASS("_TtC9AP_PaySDK15UiCustomization")
@interface UiCustomization : NSObject <PaySDKUiCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setButtonCustomization:(id <PaySDKButtonCustomization> _Nonnull)buttonCustomization :(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomization:(id <PaySDKToolbarCustomization> _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomization:(id <PaySDKLabelCustomization> _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomization:(id <PaySDKTextBoxCustomization> _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (id <PaySDKButtonCustomization> _Nullable)getButtonCustomization:(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKToolbarCustomization> _Nullable)getToolbarCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKLabelCustomization> _Nullable)getLabelCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKTextBoxCustomization> _Nullable)getTextBoxCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


typedef SWIFT_ENUM(NSInteger, payMethod, open) {
  payMethodALL = 0,
  payMethodCREDIT_CARD = 1,
  payMethodVISA = 2,
  payMethodMASTER_CARD = 3,
  payMethodJAPAN_CARD = 4,
  payMethodAMERICAN_CARD = 5,
  payMethodDINERS = 6,
  payMethodALIPAYHKAPP = 7,
  payMethodALIPAYCNAPP = 8,
  payMethodALIPAYAPP = 9,
  payMethodAPPLEPAY = 10,
  payMethodWECHATAPP = 11,
  payMethodTHREEDS2 = 12,
  payMethodCIMBCLICKS = 13,
};

typedef SWIFT_ENUM(NSInteger, payType, open) {
  payTypeNORMAL_PAYMENT = 0,
  payTypeHOLD_PAYMENT = 1,
};

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.1 effective-4.2 (swiftlang-5.7.1.134.3 clang-1400.0.29.51)
#ifndef AP_PAYSDK_SWIFT_H
#define AP_PAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PassKit;
@import StoreKit;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AP_PaySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, ApplePayButtonStyle, open) {
  ApplePayButtonStyleWhite = 0,
  ApplePayButtonStyleWhiteOutline = 1,
  ApplePayButtonStyleBlack = 2,
};

typedef SWIFT_ENUM(NSInteger, ApplePayButtonType, open) {
  ApplePayButtonTypePlain = 0,
  ApplePayButtonTypeBuy = 1,
  ApplePayButtonTypeSetUp = 2,
  ApplePayButtonTypeInStore = 3,
  ApplePayButtonTypeDonate = 4,
  ApplePayButtonTypeCheckout = 5,
  ApplePayButtonTypeBook = 6,
  ApplePayButtonTypeSubscribe = 7,
};

@class NSString;

SWIFT_PROTOCOL("_TtP9AP_PaySDK19PaySDKCustomization_")
@protocol PaySDKCustomization
- (BOOL)setTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK25PaySDKButtonCustomization_")
@protocol PaySDKButtonCustomization <PaySDKCustomization>
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonName:(NSString * _Nonnull)buttonName error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getButtonName SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK13Customization")
@interface Customization : NSObject <PaySDKCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK19ButtonCustomization")
@interface ButtonCustomization : Customization <PaySDKButtonCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSInteger)cornerRadius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSInteger)cornerRadius :(NSString * _Nonnull)buttonName OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setButtonName:(NSString * _Nonnull)buttonName error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getButtonName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("CallBackParam")
@interface CallBackParam : NSObject
- (nonnull instancetype)initWithSuccessUrl:(NSString * _Nonnull)successUrl cancelUrl:(NSString * _Nonnull)cancelUrl errorUrl:(NSString * _Nonnull)errorUrl failUrl:(NSString * _Nonnull)failUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("CardDetails")
@interface CardDetails : NSObject
- (nonnull instancetype)initWithCardHolderName:(NSString * _Nonnull)cardHolderName cardNo:(NSString * _Nonnull)cardNo expMonth:(NSString * _Nonnull)expMonth expYear:(NSString * _Nonnull)expYear securityCode:(NSString * _Nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9AP_PaySDK5Cards")
@interface Cards : NSObject
/// Instantiate the instance using the passed dictionary values to set the properties values
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CurrencyCode, open) {
  CurrencyCodeHKD = 0,
  CurrencyCodeUSD = 1,
  CurrencyCodeSGD = 2,
  CurrencyCodeRMB = 3,
  CurrencyCodeCNY = 4,
  CurrencyCodeYEN = 5,
  CurrencyCodeJPY = 6,
  CurrencyCodeTWD = 7,
  CurrencyCodeAUD = 8,
  CurrencyCodeEUR = 9,
  CurrencyCodeGBP = 10,
  CurrencyCodeCAD = 11,
  CurrencyCodeMOP = 12,
  CurrencyCodePHP = 13,
  CurrencyCodeTHB = 14,
  CurrencyCodeIDR = 15,
  CurrencyCodeBND = 16,
  CurrencyCodeMYR = 17,
  CurrencyCodeBRL = 18,
  CurrencyCodeINR = 19,
  CurrencyCodeTRY = 20,
  CurrencyCodeZAR = 21,
  CurrencyCodeVND = 22,
  CurrencyCodeLKR = 23,
  CurrencyCodeKWD = 24,
  CurrencyCodeNZD = 25,
};




typedef SWIFT_ENUM(NSInteger, EnvType, open) {
  EnvTypeSANDBOX = 0,
  EnvTypePRODUCTION = 1,
};


SWIFT_CLASS("_TtC9AP_PaySDK26GlobalJsIntegrateViewModel")
@interface GlobalJsIntegrateViewModel : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified tncUrl;
@property (nonatomic, copy) NSString * _Null_unspecified showInApp;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK24PaySDKLabelCustomization_")
@protocol PaySDKLabelCustomization <PaySDKCustomization>
- (BOOL)setHeadingTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK18LabelCustomization")
@interface LabelCustomization : Customization <PaySDKLabelCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)headingTextColor :(NSString * _Nonnull)headingTextFontName :(NSInteger)headingTextFontSize OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setHeadingTextColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontName:(NSString * _Nonnull)fontName error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeadingTextFontSize:(NSInteger)fontSize error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getHeadingTextColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeadingTextFontName SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getHeadingTextFontSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, Language, open) {
  LanguageENGLISH = 0,
  LanguageCHINESE_TRADITIONAL = 1,
  LanguageCHINESE_SIMPLIFIED = 2,
  LanguageJAPANESE = 3,
  LanguageTHAI = 4,
  LanguageFRENCH = 5,
  LanguageGERMAN = 6,
  LanguageRUSSIAN = 7,
  LanguageSPANISH = 8,
  LanguageVIETNAMESE = 9,
};


SWIFT_CLASS("_TtC9AP_PaySDK7Methods")
@interface Methods : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("OrderId")
@interface OrderId : NSObject
- (nonnull instancetype)initWithOrderId:(NSString * _Nonnull)orderId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PayChannel, open) {
  PayChannelWEBVIEW = 0,
  PayChannelDIRECT = 1,
  PayChannelEASYPAYMENTFORM = 2,
  PayChannelNONE = 3,
};

@class PresentViewController;
@class ThreeDSParams;
enum PayGate : NSInteger;
enum payType : NSInteger;

SWIFT_CLASS_NAMED("PayData")
@interface PayData : NSObject
@property (nonatomic, strong) PresentViewController * _Nullable presentController;
@property (nonatomic, strong) CardDetails * _Nullable cardDetails;
@property (nonatomic, strong) CallBackParam * _Nullable callBackParam;
@property (nonatomic, strong) ThreeDSParams * _Nullable threeDSParams;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (nonnull instancetype)initWithChannelType:(enum PayChannel)channelType envType:(enum EnvType)envType amount:(NSString * _Nonnull)amount payGate:(enum PayGate)payGate currCode:(enum CurrencyCode)currCode payType:(enum payType)payType orderRef:(NSString * _Nonnull)orderRef payMethod:(NSString * _Nonnull)payMethod lang:(enum Language)lang merchantId:(NSString * _Nonnull)merchantId remark:(NSString * _Nonnull)remark payRef:(NSString * _Nonnull)payRef resultpage:(NSString * _Nonnull)resultpage showCloseButton:(BOOL)showCloseButton showToolbar:(BOOL)showToolbar webViewClosePrompt:(NSString * _Nonnull)webViewClosePrompt extraData:(NSDictionary<NSString *, id> * _Nullable)extraData merchantCapabilitiesData:(PKMerchantCapability)merchantCapabilitiesData supportedNetworksData:(NSArray<PKPaymentNetwork> * _Nonnull)supportedNetworksData OBJC_DESIGNATED_INITIALIZER;
@end


typedef SWIFT_ENUM(NSInteger, PayGate, open) {
  PayGatePAYDOLLAR = 0,
  PayGatePESOPAY = 1,
  PayGateSIAMPAY = 2,
};


SWIFT_CLASS("_TtC9AP_PaySDK9PayResult")
@interface PayResult : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified amount;
@property (nonatomic, copy) NSString * _Null_unspecified successCode;
@property (nonatomic, copy) NSString * _Nullable maskedCardNo;
@property (nonatomic, copy) NSString * _Null_unspecified authId;
@property (nonatomic, copy) NSString * _Null_unspecified cardHolder;
@property (nonatomic, copy) NSString * _Null_unspecified currencyCode;
@property (nonatomic, copy) NSString * _Null_unspecified errMsg;
@property (nonatomic, copy) NSString * _Null_unspecified ord;
@property (nonatomic, copy) NSString * _Null_unspecified payRef;
@property (nonatomic, copy) NSString * _Null_unspecified prc;
@property (nonatomic, copy) NSString * _Null_unspecified ref;
@property (nonatomic, copy) NSString * _Null_unspecified src;
@property (nonatomic, copy) NSString * _Null_unspecified transactionTime;
@property (nonatomic, copy) NSString * _Null_unspecified descriptionStr;
@property (nonatomic, copy) NSString * _Nullable orderId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@protocol PaySDKDelegate;
@class UiCustomization;
@class NSURL;

SWIFT_CLASS_NAMED("PaySDK") SWIFT_AVAILABILITY(ios,introduced=10.0)
@interface PaySDK : NSObject <SKStoreProductViewControllerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) PaySDK * _Nonnull shared;)
+ (PaySDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(PaySDK * _Nonnull)value;
@property (nonatomic, strong) id <PaySDKDelegate> _Nullable delegate;
@property (nonatomic, strong) PayData * _Null_unspecified paymentDetails;
@property (nonatomic, strong) UiCustomization * _Nullable uiCustomization;
@property (nonatomic) BOOL isBioMetricRequired;
@property (nonatomic) BOOL useSDKProgressScreen;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (void)queryWithAction:(NSString * _Nonnull)action;
- (void)process;
- (void)processOrderWithUrl:(NSURL * _Nonnull)url;
@end


typedef SWIFT_ENUM(NSInteger, PaySDKButtonType, open) {
  PaySDKButtonTypeSUBMIT = 0,
  PaySDKButtonTypeCONTINUE = 1,
  PaySDKButtonTypeNEXT = 2,
  PaySDKButtonTypeCANCEL = 3,
  PaySDKButtonTypeRESEND = 4,
};


@class TransQueryResults;
@class PaymentOptionsDetail;
@class UIImage;
@class UIViewController;

SWIFT_PROTOCOL("_TtP9AP_PaySDK14PaySDKDelegate_")
@protocol PaySDKDelegate
- (void)paymentResultWithResult:(PayResult * _Nonnull)result;
- (void)transQueryResultsWithResult:(TransQueryResults * _Nonnull)result;
- (void)payMethodOptionsWithMethod:(PaymentOptionsDetail * _Nonnull)method;
@optional
- (void)showProgress;
- (void)hideProgress;
- (UIImage * _Nullable)setMerchantInfoImg SWIFT_WARN_UNUSED_RESULT;
- (UIViewController * _Nullable)setMerchantInfoScreen SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)setMerchantInfo SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_PROTOCOL("_TtP9AP_PaySDK26PaySDKTextBoxCustomization_")
@protocol PaySDKTextBoxCustomization <PaySDKCustomization>
- (BOOL)setBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBorderColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getBorderColor SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK26PaySDKToolbarCustomization_")
@protocol PaySDKToolbarCustomization <PaySDKCustomization>
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeaderText:(NSString * _Nonnull)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRightBarButtonText:(NSString * _Nonnull)rightBarButtonText error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getRightBarButtonText SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP9AP_PaySDK21PaySDKUiCustomization_")
@protocol PaySDKUiCustomization
- (BOOL)setButtonCustomization:(id <PaySDKButtonCustomization> _Nonnull)buttonCustomization :(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomization:(id <PaySDKToolbarCustomization> _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomization:(id <PaySDKLabelCustomization> _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomization:(id <PaySDKTextBoxCustomization> _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (id <PaySDKButtonCustomization> _Nullable)getButtonCustomization:(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKToolbarCustomization> _Nullable)getToolbarCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKLabelCustomization> _Nullable)getLabelCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKTextBoxCustomization> _Nullable)getTextBoxCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9AP_PaySDK20PaymentOptionsDetail")
@interface PaymentOptionsDetail : NSObject
@property (nonatomic, strong) Methods * _Null_unspecified methods;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("PresentViewController")
@interface PresentViewController : NSObject
- (nonnull instancetype)initWithPresentViewController:(UIViewController * _Nonnull)presentViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9AP_PaySDK20TextBoxCustomization")
@interface TextBoxCustomization : Customization <PaySDKTextBoxCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSInteger)borderWidth :(NSString * _Nonnull)borderColor :(NSInteger)cornerRadius OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setCornerRadius:(NSInteger)cornerRadius error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getCornerRadius SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setBorderWidth:(NSInteger)borderWidth error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setBorderColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (NSInteger)getBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getBorderColor SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9AP_PaySDK13ThreeDSParams") SWIFT_AVAILABILITY(ios,introduced=11.0)
@interface ThreeDSParams : NSObject
@property (nonatomic, copy) NSString * _Nullable threeDSCustomerEmail;
@property (nonatomic, copy) NSString * _Nullable threeDSDeliveryEmail;
@property (nonatomic, copy) NSString * _Nullable threeDSMobilePhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSMobilePhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSHomePhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSHomePhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSWorkPhoneCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSWorkPhoneNumber;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingState;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingCity;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine1;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine2;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingLine3;
@property (nonatomic, copy) NSString * _Nullable threeDSBillingPostalCode;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingDetails;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingCountryCode;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingState;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingCity;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine1;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine2;
@property (nonatomic, copy) NSString * _Nullable threeDSShippingLine3;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctCreateDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAgeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctLastChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctLastChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPwChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPwChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPurchaseCount;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctCardProvisionAttempt;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctNumTransDay;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctNumTransYear;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPaymentAcctDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctPaymentAcctInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctShippingAddrLastChangeDate;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctShippingAddrLastChangeInd;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctIsShippingAcctNameSame;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctIsSuspiciousAcct;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAuthMethod;
@property (nonatomic, copy) NSString * _Nullable threeDSAcctAuthTimestamp;
@property (nonatomic, copy) NSString * _Nullable threeDSDeliveryTime;
@property (nonatomic, copy) NSString * _Nullable threeDSPreOrderReason;
@property (nonatomic, copy) NSString * _Nullable threeDSPreOrderReadyDate;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardAmount;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardCurr;
@property (nonatomic, copy) NSString * _Nullable threeDSGiftCardCount;
@property (nonatomic, copy) NSString * _Nullable threeDSSdkMaxTimeout;
@property (nonatomic, copy) NSString * _Nullable threeDSSdkInterface;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9AP_PaySDK20ToolbarCustomization")
@interface ToolbarCustomization : Customization <PaySDKToolbarCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize :(NSString * _Nonnull)backgroundColor :(NSString * _Nonnull)headerText :(NSString * _Nonnull)rightBarButtonText OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setBackgroundColor:(NSString * _Nonnull)hexColorCode error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setHeaderText:(NSString * _Nonnull)headerText error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setRightBarButtonText:(NSString * _Nonnull)rightBarButtonText error:(NSError * _Nullable * _Nullable)error;
- (NSString * _Nonnull)getBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getHeaderText SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getRightBarButtonText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init:(NSString * _Nonnull)textFontName :(NSString * _Nonnull)textColor :(NSInteger)textFontSize SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("TransQueryResult")
@interface TransQueryResult : NSObject
@property (nonatomic, copy) NSString * _Nullable cur;
@property (nonatomic, copy) NSString * _Nullable txTime;
@property (nonatomic, copy) NSString * _Nullable errMsg;
@property (nonatomic, copy) NSString * _Nullable orderStatus;
@property (nonatomic, copy) NSString * _Nullable amt;
@property (nonatomic, copy) NSString * _Nullable remark;
@property (nonatomic, copy) NSString * _Nullable eci;
@property (nonatomic, copy) NSString * _Nullable ipCountry;
@property (nonatomic, copy) NSString * _Nullable channelType;
@property (nonatomic, copy) NSString * _Nullable merchantId;
@property (nonatomic, copy) NSString * _Nullable authId;
@property (nonatomic, copy) NSString * _Nullable payerAuth;
@property (nonatomic, copy) NSString * _Nullable panLast4;
@property (nonatomic, copy) NSString * _Nullable ref;
@property (nonatomic, copy) NSString * _Nullable payMethod;
@property (nonatomic, copy) NSString * _Nullable successcode;
@property (nonatomic, copy) NSString * _Nullable cardIssuingCountry;
@property (nonatomic, copy) NSString * _Nullable prc;
@property (nonatomic, copy) NSString * _Nullable ord;
@property (nonatomic, copy) NSString * _Nullable panFirst4;
@property (nonatomic, copy) NSString * _Nullable alertCode;
@property (nonatomic, copy) NSString * _Nullable src;
@property (nonatomic, copy) NSString * _Nullable payRef;
@property (nonatomic, copy) NSString * _Nullable holder;
@property (nonatomic, copy) NSString * _Nullable sourceIp;
+ (NSArray<TransQueryResult *> * _Nonnull)modelsFromDictionaryArrayWithArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
/// Returns the dictionary representation for the current instance.
///
/// returns:
/// NSDictionary.
- (NSDictionary * _Nonnull)dictionaryRepresentation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("TransQueryResults")
@interface TransQueryResults : NSObject
@property (nonatomic, copy) NSArray<TransQueryResult *> * _Nullable detail;
@property (nonatomic, copy) NSString * _Nullable errMsg;
@property (nonatomic, copy) NSString * _Nullable resultCode;
+ (NSArray<TransQueryResults *> * _Nonnull)modelsFromDictionaryArrayWithArray:(NSArray * _Nonnull)array SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


@class UIView;

@interface UIButton (SWIFT_EXTENSION(AP_PaySDK))
- (void)setApplePayButtonWithBtnType:(enum ApplePayButtonType)btnType btnStyle:(enum ApplePayButtonStyle)btnStyle inView:(UIView * _Nonnull)inView;
@end



@interface UIColor (SWIFT_EXTENSION(AP_PaySDK))
- (nullable instancetype)initWithHex:(NSString * _Nonnull)hex;
@end











SWIFT_CLASS("_TtC9AP_PaySDK15UiCustomization")
@interface UiCustomization : NSObject <PaySDKUiCustomization>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)setButtonCustomization:(id <PaySDKButtonCustomization> _Nonnull)buttonCustomization :(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setToolbarCustomization:(id <PaySDKToolbarCustomization> _Nonnull)toolbarCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setLabelCustomization:(id <PaySDKLabelCustomization> _Nonnull)labelCustomization error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setTextBoxCustomization:(id <PaySDKTextBoxCustomization> _Nonnull)textBoxCustomization error:(NSError * _Nullable * _Nullable)error;
- (id <PaySDKButtonCustomization> _Nullable)getButtonCustomization:(enum PaySDKButtonType)buttonType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKToolbarCustomization> _Nullable)getToolbarCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKLabelCustomization> _Nullable)getLabelCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (id <PaySDKTextBoxCustomization> _Nullable)getTextBoxCustomizationAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end


typedef SWIFT_ENUM(NSInteger, payMethod, open) {
  payMethodALL = 0,
  payMethodCREDIT_CARD = 1,
  payMethodVISA = 2,
  payMethodMASTER_CARD = 3,
  payMethodJAPAN_CARD = 4,
  payMethodAMERICAN_CARD = 5,
  payMethodDINERS = 6,
  payMethodALIPAYHKAPP = 7,
  payMethodALIPAYCNAPP = 8,
  payMethodALIPAYAPP = 9,
  payMethodAPPLEPAY = 10,
  payMethodWECHATAPP = 11,
  payMethodTHREEDS2 = 12,
  payMethodCIMBCLICKS = 13,
};

typedef SWIFT_ENUM(NSInteger, payType, open) {
  payTypeNORMAL_PAYMENT = 0,
  payTypeHOLD_PAYMENT = 1,
};

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif

#endif
